### ISSUE TITLE
mac defaults/config

### ISSUE THREAD

**Issue by naggie** [naggie/dotfiles#122]
- [ ] paste and match style by default https://furbo.org/2015/03/30/paste-without-style/
- [ ] display: scaled to highest resolution
- [ ] power saving: do not sleep (unless closed and on battery)
- [ ] screensaver --  turn off screen + lock after 5 mins
- [ ] show battery percentage
- [ ] 24h time with seconds
- [ ] remap caps lock to esc https://github.com/mathiasbynens/dotfiles/issues/310
- [ ] set key repeat / delay to as fast as possible
- [ ] spotlight indexing -- limit to applications, exclude home folder, turn off useless web features (and figure out how not to clobber mail smart inboxes)
- [ ] enable dark mode
- [ ] enable night shift on max turbo setting

![image](https://user-images.githubusercontent.com/208440/36964956-11d86dd0-2050-11e8-94e7-b2ea3907b0d8.png)

see also https://support.serato.com/hc/en-us/articles/202833544

**Comment by fgilio** [comment]
There seems to be a way to automate the caps lock mapping https://stackoverflow.com/a/46460200/3275796

**Comment by naggie** [comment]
Thanks!
