### ISSUE TITLE
Full FZF integration

### ISSUE THREAD

**Issue by naggie** [naggie/dotfiles#147]
- [x] install fzf on all platforms
- [x] fzf vim somehow
- [x] map fzf to ctrlp inside shell (open vim)
- [x] map fzf to ctrlp inside vim
- [x] enter should open in new tab by default https://github.com/junegunn/fzf/wiki/Examples-(vim)#open-files-in-splits (not on empty buffer, see ctrlp config)
- [x] bash completion
- [x] remove ctrlp
- [x] other completions in fzf readme
- [x] shell history search $(brew --prefix)/opt/fzf/install
- [x] replacement for findack (maybe alias: f)
- [x] ctrl-t to enter as an argument https://dmerej.info/blog/post/fzf-for-the-win/ $(brew --prefix)/opt/fzf/install
- [x] install ~fd~ ripgrep on all platforms and deprecate ack
- [x] update README with new bindings/software
- [x] ctrl+r history dedup either via FZF for cleanup script when bash exits (looks like the best option is python dedup leaving cmd at last location, should work backwards)
- [x] export FZF_CTRL_T_COMMAND FZF_DEFAULT_COMMAND='find --type f --hidden --follow --exclude .git' etc see https://github.com/junegunn/fzf#respecting-gitignore -- can use fd or `ripgrep --files --hidden` .git is already ignored
- [x] merge into master when stable
- [x] FZF_DEFAULT_OPS --history-size=9000 ? (or change bash to save only 1000 now that dedup reduces the number of lines required, measured to be about 2-3x) 1000 is fine as cleanup script makes history effectively LRU collected
- [x] decide either to use vim FZF or FZF | args $EDITOR outside of vim (then it becomes editor independent
- [x] FZF in vim --  git root https://github.com/junegunn/fzf.vim/issues/47#issuecomment-160237795 or https://github.com/airblade/vim-rooter
- [x] test all on bash/fish/zsh/vim/neovim
- [ ] https://github.com/junegunn/fzf/wiki/Examples-(vim)#search-lines-in-all-open-vim-buffers ? -- link to ctrl+l
- [x] ~fish completions etc https://github.com/junegunn/fzf/wiki/Examples-(fish) https://github.com/jethrokuan/fzf (especially ctrl+r)~
- [ ] `rgfzf` - alike inside vim?
https://github.com/junegunn/fzf.vim/issues/47#issuecomment-160237795
- [ ] also investigate possibility of bash command completion https://github.com/junegunn/fzf/blob/master/shell/completion.bash
- [ ] git branch completions?
- [x] ~pass completions~ bash completions are good enough
- [ ] ctrlp and fzf outside vim should get git root I think
- [x] ctrl p may as well be a command to avoid duplication of code

https://github.com/junegunn/fzf/wiki/Examples-(completion)
